---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: botbot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: botbot 
  name: botbot
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi