apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: botbot
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: botbot 
  name: botbot
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: botbot 
    weight: 100 
  wildcardPolicy: None
