apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-botbot-gitops
spec:  
  template:         
    metadata:
      name: dsp-clone-job-botbot-gitops
    spec:  
      serviceAccountName: botbot-dsp-job
      containers:
      - name: initialize-dsp
        image: quay.io/redhat-ai-dev/utils:latest
        command:
        - /bin/bash
        - -c
        - |
          NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
          oc wait -l statefulset=botbot-notebook --for=condition=ready pod --timeout=300s
          oc exec  StatefulSet/botbot-notebook -- git clone https://github.com/jrichter-rhtap/bot3
      restartPolicy: Never